instrumentation:
  root: ./dist-spec
  include-all-sources: true
  verbose: true
  excludes: ['**/*.spec.js', '**/spec/**/*.js', '**/build/**/*.js']
reporting:
  dir: 'coverage'
  reports:
    - lcovonly
